include:
  - project: 'takamol/qiwa/infrastructure/ci-cd'
    file: '/common-jobs/.package-docker-image.yml'
  - project: 'takamol/qiwa/infrastructure/ci-cd'
    file: '/common-jobs/.sonarqube-check.yml'
  - project: 'takamol/qiwa/infrastructure/ci-cd'
    file: '/common-jobs/.allure-report.yml'

variables:
  IMAGE: takamol/qa-automation:master-latest
  ALLURE_RESULTS_DIRECTORY: allure-results

stages:
  - build
  - linting
  - tests
  - send-test-reports

.package:
  image: takamol/ci-cd:package-latest
  services:
    - name: docker:dind
  script:
    - echo $TAKAMOL_REGISTRY_PASSWORD | docker login -u $TAKAMOL_REGISTRY_USERNAME --password-stdin
    - docker pull $ENV_LATEST || true
    - docker build --cache-from $ENV_LATEST --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --build-arg CI_SERVER_HOST=${CI_SERVER_HOST} -t $ENV_LATEST -t $VERSION_TAGGED .
    - docker push $ENV_LATEST
    - docker push $VERSION_TAGGED
    - echo "Image name $VERSION_TAGGED"

build:
  stage: build
  extends: .package
  variables:
    ENV: master
  tags:
    - dind
  only:
    refs:
      - web
      - merge_requests
    changes:
      - Dockerfile
      - pyproject.toml

build_test_allure:
  stage: build
  extends: .package
  tags:
    - dind
  variables:
    ENV: testallure
  only:
    - add_allure_cleaner

pylint:
  image: $IMAGE
  stage: linting
  tags:
    - shared
  before_script:
    - mkdir -p public/badges public/lint
    - echo undefined > public/badges/$CI_JOB_NAME.score
  script:
    - pylint --exit-zero --output-format=text $(find -type f -name "*.py" ! -path "**/.venv/**") | tee /tmp/pylint.txt
    - sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' /tmp/pylint.txt > public/badges/$CI_JOB_NAME.score
    - pylint --exit-zero --output-format=pylint_gitlab.GitlabCodeClimateReporter $(find -type f -name "*.py" ! -path "**/.venv/**") > codeclimate.json
    - pylint --exit-zero --output-format=pylint_gitlab.GitlabPagesHtmlReporter $(find -type f -name "*.py" ! -path "**/.venv/**") > public/lint/index.html
    - if [ $(cat public/badges/$CI_JOB_NAME.score) != 10.00 ]; then exit 1; fi
  after_script:
    - anybadge --overwrite --label $CI_JOB_NAME --value=$(cat public/badges/$CI_JOB_NAME.score) --file=public/badges/$CI_JOB_NAME.svg 4=red 6=orange 8=yellow 10=green
    - |
      echo "Your score is: $(cat public/badges/$CI_JOB_NAME.score)"
  artifacts:
    paths:
      - public
    reports:
      codequality: codeclimate.json
    when: always
  only:
      - merge_requests

black:
  image: $IMAGE
  stage: linting
  script:
    - black . --check --diff --color
  only:
    - merge_requests

isort:
  image: $IMAGE
  stage: linting
  script:
    - isort . --check --diff
  only:
    - merge_requests

ui_tests_sso:
  image: takamol/qa-automation:$ENV-latest
  allow_failure: true
  stage: tests
  tags:
    - shared
  script:
    - pytest tests/ui/sso -s --alluredir=allure-results
  retry:
    max: 2
    when: always
  artifacts:
    paths:
      - $ALLURE_RESULTS_DIRECTORY
    expire_in: 1 day
    when: always
  variables:
    ENV: master
  only:
    - master

ui_tests_um:
  image: $IMAGE
  allow_failure: true
  stage: tests
  tags:
    - shared
  script:
    - pytest tests/ui/um -s --alluredir=allure-results --discord_channel=um-ui-daily
  artifacts:
    paths:
      - $ALLURE_RESULTS_DIRECTORY
    expire_in: 1 day
    when: always
  variables:
    ENV: stage
  only:
    - master

ui_tests_shareable:
  image: takamol/qa-automation:$ENV-latest
  allow_failure: true
  stage: tests
  tags:
    - shared
  script:
    - pytest tests/ui/shareable -s --alluredir=allure-results --reruns 2 --discord_channel=ss-ui-wp-daily
  artifacts:
    paths:
      - $ALLURE_RESULTS_DIRECTORY
    expire_in: 1 day
    when: always
  variables:
    ENV: master
  only:
    - master

ui_tests_dedicated:
  image: $IMAGE
  allow_failure: true
  stage: tests
  tags:
    - shared
  script:
    - pytest tests/ui/dedicated -s --alluredir=allure-results
  artifacts:
    paths:
      - $ALLURE_RESULTS_DIRECTORY
    expire_in: 1 day
    when: always
  variables:
    ENV: demo
  only:
    - master

api_tests_sso:
  image: $IMAGE
  allow_failure: true
  stage: tests
  tags:
    - shared
  script:
    - pytest tests/api/sso -s --alluredir=allure-results --reruns 2
  artifacts:
    paths:
      - $ALLURE_RESULTS_DIRECTORY
    expire_in: 1 day
    when: always
  variables:
    ENV: master
  only:
    - master

api_tests_um:
  image: $IMAGE
  allow_failure: true
  stage: tests
  tags:
    - shared
  script:
    - pytest tests/api/um -s --alluredir=allure-results --discord_channel=um-api-daily
  artifacts:
    paths:
      - $ALLURE_RESULTS_DIRECTORY
    expire_in: 1 day
    when: always
  variables:
    ENV: stage
  only:
    - master

api_tests_shareable_demo:
  image: $IMAGE
  allow_failure: true
  stage: tests
  tags:
    - shared
  script:
    - pytest tests/api/shareable -s --alluredir=allure-results --discord_channel=ss-api-wp-daily
  artifacts:
    paths:
      - $ALLURE_RESULTS_DIRECTORY
    expire_in: 1 day
    when: always
  variables:
    ENV: master
  only:
    - master

api_tests_shareable_stage:
  image: takamol/qa-automation:master-latest
  allow_failure: true
  stage: tests
  tags:
    - shared
  script:
     - pytest tests/api/shareable -m stage -s --alluredir=allure-results --discord_channel=ss-api-wp-daily
  artifacts:
    paths:
      - $ALLURE_RESULTS_DIRECTORY
    expire_in: 1 day
    when: always
  variables:
    ENV: stage
  only:
    - master

allure-ui-sso-results:
  extends: .generate_allure_report
  stage: send-test-reports
  variables:
    ALLURE_PROJECT_ID: v1-sso-ui-daily
  dependencies:
    - ui_tests_sso
  needs:
    - ui_tests_sso
  only:
    - master

allure-ui-um-results:
  extends: .generate_allure_report
  stage: send-test-reports
  variables:
    ALLURE_PROJECT_ID: um-ui-daily
  dependencies:
    - ui_tests_um
  needs:
    - ui_tests_um
  only:
    - master


allure-ss-ui-wp-results:
  extends: .generate_allure_report
  stage: send-test-reports
  variables:
    ALLURE_PROJECT_ID: ss-ui-wp-daily
  dependencies:
    - ui_tests_shareable
  needs:
    - ui_tests_shareable
  only:
    - master

allure-ui-et-results:
  extends: .generate_allure_report
  stage: send-test-reports
  variables:
    ALLURE_PROJECT_ID: et-ui-daily
  dependencies:
    - ui_tests_dedicated
  needs:
    - ui_tests_dedicated
  only:
    - stage


allure-api-sso-results:
  extends: .generate_allure_report
  stage: send-test-reports
  variables:
    ALLURE_PROJECT_ID: v1-sso-api-daily
  dependencies:
    - api_tests_sso
  needs:
    - api_tests_sso
  only:
    - master

allure-api-um-results:
  extends: .generate_allure_report
  stage: send-test-reports
  variables:
    ALLURE_PROJECT_ID: um-api-daily
  dependencies:
    - api_tests_um
  needs:
    - api_tests_um
  only:
    - master

allure-api-wp-results:
  extends: .generate_allure_report
  stage: send-test-reports
  variables:
    ALLURE_PROJECT_ID: ss-api-wp-daily
  dependencies:
    - api_tests_shareable_demo
  needs:
    - api_tests_shareable_demo
  only:
    - master

allure-api-ss-stage-results:
  extends: .generate_allure_report
  stage: send-test-reports
  variables:
    ALLURE_PROJECT_ID: ss-api-stage
  dependencies:
    - api_tests_shareable_stage
  needs:
    - api_tests_shareable_stage
  only:
    - master
