include:
  - project: 'takamol/qiwa/infrastructure/ci-cd'
    file: '/common-jobs/.package-docker-image.yml'
  - project: 'takamol/qiwa/infrastructure/ci-cd'
    file: '/common-jobs/.sonarqube-check.yml'
  - project: 'takamol/qiwa/infrastructure/ci-cd'
    file: '/common-jobs/.allure-report.yml'

variables:
  IMAGE: takamol/qiwa-automation:master-latest
  ALLURE_RESULTS_DIRECTORY: allure-results
  XML_REPORT: report.xml
  TESTMO_URL: https://qiwa.testmo.net


stages:
  - build
  - linting
  - test-run
  - testmo-report
  - allure-report
  - discord-notification

.package:
  image: $CI_REGISTRY/takamol/qiwa/infrastructure/ci-cd/package:latest
  services:
    - name: docker:dind
  script:
    - echo $TAKAMOL_REGISTRY_PASSWORD | docker login -u $TAKAMOL_REGISTRY_USERNAME --password-stdin
    - docker pull $ENV_LATEST || true
    - docker build --cache-from $ENV_LATEST --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --build-arg CI_SERVER_HOST=${CI_SERVER_HOST} -t $ENV_LATEST -t $VERSION_TAGGED .
    - docker push $ENV_LATEST
    - docker push $VERSION_TAGGED
    - echo "Image name $VERSION_TAGGED"

build:
  stage: build
  extends: .package
  variables:
    ENV: master
  tags:
    - dind
  only:
    refs:
      - web
      - merge_requests
    changes:
      - Dockerfile
      - pyproject.toml

build_test_allure:
  stage: build
  extends: .package
  tags:
    - dind
  only:
    - add_allure_cleaner

pylint:
  image: $IMAGE
  stage: linting
  tags:
    - shared
  before_script:
    - mkdir -p public/badges public/lint
    - echo undefined > public/badges/$CI_JOB_NAME.score
  script:
    - echo CI_COMMIT_SHA=${CI_COMMIT_SHA}
    - echo CI_MERGE_REQUEST_TARGET_BRANCH_NAME=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
    - git fetch origin ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
    - tmp_files=$(git diff --name-only ${CI_COMMIT_SHA} origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME})
    - echo "Changed files are $tmp_files"
    - if [ -z "$(echo "$tmp_files" | grep "\.py")" ]; then exit 0; else echo "Python files are found"; fi
    - tmp_pfiles=$(echo "$tmp_files" | grep "\.py")
    - echo "Python files are $tmp_pfiles"
    - pylint --exit-zero --output-format=text $tmp_pfiles | tee /tmp/pylint.txt
    - sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' /tmp/pylint.txt > public/badges/$CI_JOB_NAME.score
    - pylint --exit-zero --output-format=pylint_gitlab.GitlabCodeClimateReporter $tmp_pfiles > codeclimate.json
    - pylint --exit-zero --output-format=pylint_gitlab.GitlabPagesHtmlReporter $tmp_pfiles > public/lint/index.html
    - if [ $(cat public/badges/$CI_JOB_NAME.score) != 10.00 ]; then exit 1; fi
  after_script:
    - anybadge
      --overwrite
      --label $CI_JOB_NAME
      --value=$(cat public/badges/$CI_JOB_NAME.score)
      --file=public/badges/$CI_JOB_NAME.svg 4=red 6=orange 8=yellow 10=green
    - |
      echo "Your score is: $(cat public/badges/$CI_JOB_NAME.score)"
  artifacts:
    paths:
      - public
    reports:
      codequality: codeclimate.json
    when: always
  only:
      - merge_requests

black:
  image: $IMAGE
  stage: linting
  script:
    - black . --check --diff --color
  only:
    - merge_requests

isort:
  image: $IMAGE
  stage: linting
  script:
    - isort . --check --diff
  only:
    - merge_requests

.testrun_template: &testrun
  image: $IMAGE
  allow_failure:
    exit_codes: 1
  stage: test-run
  timeout: 150 minutes
  tags:
    - shared
  script:
    - echo $TEST_SUITE
    - pytest $TEST_SUITE $OPTIONS -s --alluredir=$ALLURE_RESULTS_DIRECTORY --junitxml=$XML_REPORT --reruns 2 -o junit_suite_name=$TEST_SUITE || EXIT_CODE=$?
    - exit $EXIT_CODE
  artifacts:
    paths:
      - $XML_REPORT
      - $ALLURE_RESULTS_DIRECTORY
    expire_in: 1 day
    when: always
  only:
    - master

sso_ui_tests:
  <<: *testrun
  variables:
    ENV: demo
    TEST_SUITE: tests/ui/sso

um_ui_tests:
  <<: *testrun
  variables:
    ENV: stage
    TEST_SUITE: tests/ui/um

shareable_ui_tests:
  <<: *testrun
  variables:
    ENV: demo
    TEST_SUITE: tests/ui/shareable

dedicated_co_ui_tests:
  <<: *testrun
  variables:
    ENV: stage
    TEST_SUITE: tests/ui/dedicated/change_occupation

visa_ui_tests:
  <<: *testrun
  variables:
    ENV: demo
    TEST_SUITE: tests/ui/visa

dataportal_ui_tests:
  <<: *testrun
  variables:
    ENV: stage
    TEST_SUITE: tests/ui/dataportal

lmi_ui_tests:
  <<: *testrun
  variables:
    ENV: stage
    TEST_SUITE: tests/ui/lmi

sso_api_tests:
  <<: *testrun
  variables:
    ENV: stage
    TEST_SUITE: tests/api/sso

um_api_tests:
  <<: *testrun
  variables:
    ENV: stage
    TEST_SUITE: tests/api/um

shareable_demo_api_tests:
  <<: *testrun
  variables:
    ENV: demo
    TEST_SUITE: tests/api/shareable

shareable_stage_api_tests:
  <<: *testrun
  variables:
    ENV: stage
    TEST_SUITE: tests/api/shareable
    OPTIONS: "-m stage"

lmi_api_tests:
  <<: *testrun
  variables:
    ENV: stage
    TEST_SUITE: tests/api/lmi

.testmo_report_template: &testmo_report
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  stage: testmo-report
  image: $IMAGE
  script:
    - echo $TESTMO_PROJECT_ID
    - echo $ALLURE_PROJECT_ID
    - testmo automation:resources:add-link
      --name "Allure report"
      --url "https://allure.qiwa.tech/allure-docker-service-ui/projects/$ALLURE_PROJECT_ID"
      --note "Allure contains more advanced reports of the test runs"
    - testmo automation:resources:add-link
      --name "GitLab CI/CD pipeline"
      --url "https://gitlab.qiwa.tech/takamol/qiwa/integration-testing/qiwa-automation/-/jobs/$CI_JOB_ID"
      --note "Link to GitLab's CI/CD job logs"
    - testmo automation:run:submit
      --instance $TESTMO_URL
      --project-id $TESTMO_PROJECT_ID
      --name "Pytest test run"
      --source "CI-CD"
      --results $XML_REPORT
      --debug
      --resources testmo-resources.json

sso_ui_testmo_report:
  <<: *testmo_report
  variables:
    TESTMO_PROJECT_ID: 23
    ALLURE_PROJECT_ID: sso-ui-daily
  needs: [sso_ui_tests]

um_ui_testmo_report:
  <<: *testmo_report
  variables:
    TESTMO_PROJECT_ID: 26
    ALLURE_PROJECT_ID: um-ui-daily
  needs: [um_ui_tests]

dedicated_co_ui_testmo_report:
  <<: *testmo_report
  variables:
    TESTMO_PROJECT_ID: 3
    ALLURE_PROJECT_ID: co-ui-daily
  needs: [dedicated_co_ui_tests]

visa_ui_testmo_report:
  <<: *testmo_report
  variables:
    TESTMO_PROJECT_ID: 7
    ALLURE_PROJECT_ID: visa-ui-tests
  needs: [visa_ui_tests]

dataportal_ui_testmo_report:
  <<: *testmo_report
  variables:
    TESTMO_PROJECT_ID: 15
    ALLURE_PROJECT_ID: dataportal-ui-daily
  needs: [dataportal_ui_tests]

lmi_ui_testmo_report:
  <<: *testmo_report
  variables:
    TESTMO_PROJECT_ID: 15
    ALLURE_PROJECT_ID: lmi-ui-daily
  needs: [lmi_ui_tests]

sso_api_testmo_report:
  <<: *testmo_report
  variables:
    TESTMO_PROJECT_ID: 23
    ALLURE_PROJECT_ID: sso-api-daily
  needs: [sso_api_tests]

um_api_testmo_report:
  <<: *testmo_report
  variables:
    TESTMO_PROJECT_ID: 26
    ALLURE_PROJECT_ID: um-api-daily
  needs: [um_api_tests]

lmi_api_testmo_report:
  <<: *testmo_report
  variables:
    TESTMO_PROJECT_ID: 15
    ALLURE_PROJECT_ID: lmi-api-daily
  needs: [lmi_api_tests]

.allure_report_template: &allure_report
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  extends: .generate_allure_report
  stage: allure-report

sso_ui_allure_report:
  <<: *allure_report
  variables:
    ALLURE_PROJECT_ID: v1-sso-ui-daily
  needs: [sso_ui_tests]

um_ui_allure_report:
  <<: *allure_report
  variables:
    ALLURE_PROJECT_ID: um-ui-daily
  needs: [um_ui_tests]

shareable_ui_allure_report:
  <<: *allure_report
  variables:
    ALLURE_PROJECT_ID: ss-ui-wp-daily
  needs: [shareable_ui_tests]

dedicated_co_ui_allure_report:
  <<: *allure_report
  variables:
    ALLURE_PROJECT_ID: co-ui-daily
  needs: [dedicated_co_ui_tests]

dataportal_ui_allure_report:
  <<: *allure_report
  variables:
    ALLURE_PROJECT_ID: dataportal-ui-daily
  needs: [dataportal_ui_tests]

lmi_ui_allure_report:
  <<: *allure_report
  variables:
    ALLURE_PROJECT_ID: lmi-ui-daily
  needs: [lmi_ui_tests]

sso_api_allure_report:
  <<: *allure_report
  variables:
    ALLURE_PROJECT_ID: v1-sso-api-daily
  needs: [sso_api_tests]

um_api_allure_report:
  <<: *allure_report
  variables:
    ALLURE_PROJECT_ID: um-api-daily
  needs: [um_api_tests]

shareable_demo_api_allure_report:
  <<: *allure_report
  variables:
    ALLURE_PROJECT_ID: ss-api-wp-daily
  needs: [shareable_demo_api_tests]

shareable_stage_api_allure_report:
  <<: *allure_report
  variables:
    ALLURE_PROJECT_ID: ss-api-stage
  needs: [shareable_stage_api_tests]

lmi_api_allure_report:
  <<: *allure_report
  variables:
    ALLURE_PROJECT_ID: lmi-api-daily
  needs: [lmi_api_tests]

.discord_notification_template: &discord_notification
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  stage: discord-notification
  image: $IMAGE
  script:
    - python utils/discord_notify.py $XML_REPORT $WEBHOOK

um_ui_discord_notification:
  <<: *discord_notification
  variables:
    WEBHOOK: $UM_UI_DAILY
  needs: [um_ui_tests]

shareable_ui_discord_notification:
  <<: *discord_notification
  variables:
    WEBHOOK: $SS_UI_WP_DAILY
  needs: [shareable_ui_tests]

um_api_discord_notification:
  <<: *discord_notification
  variables:
    WEBHOOK: $UM_API_DAILY
  needs: [um_api_tests]

shareable_demo_api_discord_notification:
  <<: *discord_notification
  variables:
    WEBHOOK: $SS_API_WP_DAILY
  needs: [shareable_demo_api_tests]

shareable_stage_api_discord_notification:
  <<: *discord_notification
  variables:
    WEBHOOK: $SS_API_WP_DAILY
  needs: [shareable_stage_api_tests]