include:
  - project: 'takamol/qiwa/infrastructure/ci-cd'
    file: '/common-jobs/.package-docker-image.yml'
  - project: 'takamol/qiwa/infrastructure/ci-cd'
    file: '/common-jobs/.sonarqube-check.yml'
  - project: 'takamol/qiwa/infrastructure/ci-cd'
    file: '/common-jobs/.allure-report.yml'

variables:
  IMAGE: takamol/qiwa-automation:master-latest
  ALLURE_DIRECTORY: allure-results
  XML_REPORT: report.xml

stages:
  - build
  - linting
  - tests
  - send-test-reports
  - notification

.package:
  image: takamol/ci-cd:package-latest
  services:
    - name: docker:dind
  script:
    - echo $TAKAMOL_REGISTRY_PASSWORD | docker login -u $TAKAMOL_REGISTRY_USERNAME --password-stdin
    - docker pull $ENV_LATEST || true
    - docker build --cache-from $ENV_LATEST --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --build-arg CI_SERVER_HOST=${CI_SERVER_HOST} -t $ENV_LATEST -t $VERSION_TAGGED .
    - docker push $ENV_LATEST
    - docker push $VERSION_TAGGED
    - echo "Image name $VERSION_TAGGED"

build:
  stage: build
  extends: .package
  variables:
    ENV: master
  tags:
    - dind
  only:
    refs:
      - web
      - merge_requests
    changes:
      - Dockerfile
      - pyproject.toml

build_test_allure:
  stage: build
  extends: .package
  tags:
    - dind
  only:
    - add_allure_cleaner

pylint:
  image: $IMAGE
  stage: linting
  tags:
    - shared
  before_script:
    - mkdir -p public/badges public/lint
    - echo undefined > public/badges/$CI_JOB_NAME.score
  script:
    - pylint --exit-zero --output-format=text $(find -type f -name "*.py" ! -path "**/.venv/**") | tee /tmp/pylint.txt
    - sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' /tmp/pylint.txt > public/badges/$CI_JOB_NAME.score
    - pylint --exit-zero --output-format=pylint_gitlab.GitlabCodeClimateReporter $(find -type f -name "*.py" ! -path "**/.venv/**") > codeclimate.json
    - pylint --exit-zero --output-format=pylint_gitlab.GitlabPagesHtmlReporter $(find -type f -name "*.py" ! -path "**/.venv/**") > public/lint/index.html
    - if [ $(cat public/badges/$CI_JOB_NAME.score) != 10.00 ]; then exit 1; fi
  after_script:
    - anybadge --overwrite --label $CI_JOB_NAME --value=$(cat public/badges/$CI_JOB_NAME.score) --file=public/badges/$CI_JOB_NAME.svg 4=red 6=orange 8=yellow 10=green
    - |
      echo "Your score is: $(cat public/badges/$CI_JOB_NAME.score)"
  artifacts:
    paths:
      - public
    reports:
      codequality: codeclimate.json
    when: always
  only:
      - merge_requests

black:
  image: $IMAGE
  stage: linting
  script:
    - black . --check --diff --color
  only:
    - merge_requests

isort:
  image: $IMAGE
  stage: linting
  script:
    - isort . --check --diff
  only:
    - merge_requests

.testrun_template: &testrun
  image: $IMAGE
  allow_failure:
    exit_codes: 1
  stage: tests
  tags:
    - shared
  script:
    - echo $TEST_SUITE
    - pytest $TEST_SUITE $OPTIONS -s --alluredir=$ALLURE_DIRECTORY --junitxml=$XML_REPORT -o junit_suite_name=$TEST_SUITE || EXIT_CODE=$?
    - exit $EXIT_CODE
  artifacts:
    paths:
      - $XML_REPORT
      - $ALLURE_DIRECTORY
    expire_in: 1 day
  variables:
    ENV: demo

ui_tests_sso:
  <<: *testrun
  variables:
    TEST_SUITE: tests/ui/sso

ui_tests_um:
  <<: *testrun
  variables:
    ENV: stage
    TEST_SUITE: tests/ui/um

ui_tests_shareable:
  <<: *testrun
  variables:
    TEST_SUITE: tests/ui/shareable


ui_tests_dedicated:
  <<: *testrun
  variables:
    TEST_SUITE: tests/ui/dedicated

api_tests_sso:
  <<: *testrun
  variables:
    TEST_SUITE: tests/api/sso

api_tests_um:
  <<: *testrun
  variables:
    ENV: stage
    TEST_SUITE: tests/api/um

api_tests_shareable_demo:
  <<: *testrun
  variables:
    TEST_SUITE: tests/api/shareable

api_tests_shareable_stage:
  <<: *testrun
  variables:
    ENV: stage
    TEST_SUITE: tests/api/shareable
    OPTIONS: "-m stage"

.allure_results_template: &test_results
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  extends: .generate_allure_report
  stage: send-test-reports

allure-ui-sso-results:
  <<: *test_results
  variables:
    ALLURE_PROJECT_ID: v1-sso-ui-daily
  needs: [ui_tests_sso]

allure-ui-um-results:
  <<: *test_results
  variables:
    ALLURE_PROJECT_ID: um-ui-daily
  needs: [ui_tests_um]

allure-ss-ui-wp-results:
  <<: *test_results
  variables:
    ALLURE_PROJECT_ID: ss-ui-wp-daily
  needs: [ui_tests_shareable]

allure-ui-et-results:
  <<: *test_results
  variables:
    ALLURE_PROJECT_ID: et-ui-daily
  needs: [ui_tests_dedicated]

allure-api-sso-results:
  <<: *test_results
  variables:
    ALLURE_PROJECT_ID: v1-sso-api-daily
  needs: [api_tests_sso]

allure-api-um-results:
  <<: *test_results
  variables:
    ALLURE_PROJECT_ID: um-api-daily
  needs: [api_tests_um]

allure-api-wp-results:
  <<: *test_results
  variables:
    ALLURE_PROJECT_ID: ss-api-wp-daily
  needs: [api_tests_shareable_demo]

allure-api-ss-stage-results:
  <<: *test_results
  variables:
    ALLURE_PROJECT_ID: ss-api-stage
  needs: [api_tests_shareable_stage]

.discord_notification_template: &discord_notification
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  stage: notification
  image: $IMAGE
  script:
    - python utils/discord_notify.py $XML_REPORT $WEBHOOK

discord_um_ui_notification:
  <<: *discord_notification
  variables:
    WEBHOOK: $UM_UI_DAILY
  needs: [ui_tests_um]

discord_ss_ui_notification:
  <<: *discord_notification
  variables:
    WEBHOOK: $SS_UI_WP_DAILY
  needs: [ui_tests_shareable]

discord_um_api_notification:
  <<: *discord_notification
  variables:
    WEBHOOK: $UM_API_DAILY
  needs: [api_tests_um]

discord_ss_api_demo_notification:
  <<: *discord_notification
  variables:
    WEBHOOK: $SS_API_WP_DAILY
  needs: [api_tests_shareable_demo]

discord_ss_api_stage_notification:
  <<: *discord_notification
  variables:
    WEBHOOK: $SS_API_WP_DAILY
  needs: [api_tests_shareable_stage]